### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by plclmezboss** [jonathanmli/Avalon-LLM#1]
Hello, after running the command python -m src.start_task -s avalon-dev-naive 3, I encountered this screen. Could you please tell me what the problem is?
![1701421670000](https://github.com/jonathanmli/Avalon-LLM/assets/72842813/e3e07625-25b1-46d3-a4af-9ecd0937e9f7)

**Comment by HenryCai11** [comment]
Hi, yeah it's the normal output. And then you need to open a new terminal and start the assignment with `python -m src.assigner --config ./configs/assignments/test_avalon.yaml`

**Comment by plclmezboss** [comment]
thank u so much!

**Comment by plclmezboss** [comment]
I apologize for disturbing you again, but I followed your instructions, and the output still seems to be incorrect.
![1701543926526](https://github.com/jonathanmli/Avalon-LLM/assets/72842813/4d2bb911-8866-4a63-9e94-14f3f7b6231c)

**Comment by HenryCai11** [comment]
@plclmezboss Sorry for missing this message. How's the issue now? Maybe you can try rerunning this command when running into problems at this stage. Feel free to reach out if there are still any issues!
